#!/bin/bash -x

export REPO_TOP=../../../../../..
VF=$REPO_TOP/bin/VeriForge

# uncomment to run xsim/vivado
$VF $REPO_TOP/tests/hw/ip/hello/dv/hello_sim_cfg_xsim.hjson

# uncomment to run verilator
$VF $REPO_TOP/tests/hw/ip/hello/dv/hello_sim_cfg_verilator.hjson

