#!/bin/bash -x

export REPO_TOP=/home/viraphol/prj/siliconforge/opentitan

# uncomment to run xsim/vivado
$REPO_TOP/util/dvsim/dvsim.py $REPO_TOP/hw/ip/hello/dv/hello_sim_cfg_xsim.hjson

# uncomment to run verilator 
#$REPO_TOP/util/dvsim/dvsim.py $REPO_TOP/hw/ip/hello/dv/hello_sim_cfg_verilator.hjson
